# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "yard-pygments"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan Weizenbaum", "Nicos Gollan"]
  s.date = "2012-03-26"
  s.description = "A plugin for the YARD documentation system that adds syntax highlighting\nfor a wide variety of languages using the Pygments highlighter.\n"
  s.email = "gtdev@spearhead.de"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".yardopts",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/yard-pygments.rb",
    "templates/default/fulldoc/html/pygments.erb",
    "templates/default/fulldoc/html/setup.rb",
    "templates/default/layout/html/headers.erb",
    "yard-pygments.gemspec"
  ]
  s.homepage = "http://github.com/ngollan/yard-pygments"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.19"
  s.summary = "Pygments-based syntax highlighting for YARD."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<rb-pygments>, [">= 0.1.0"])
    else
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<rb-pygments>, [">= 0.1.0"])
    end
  else
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<rb-pygments>, [">= 0.1.0"])
  end
end

